sql
CREATE DATABASE IF NOT EXISTS `zucks`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `zucks`;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(64) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `stats` (
  `id` INT PRIMARY KEY,
  `guilds` INT DEFAULT 0,
  `users` INT DEFAULT 0,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `guilds` (
  `id` VARCHAR(32) PRIMARY KEY,
  `name` VARCHAR(255),
  `icon` VARCHAR(512),
  `member_count` INT DEFAULT 0,
  `owner_id` VARCHAR(32),
  `joined_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `logs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `event` VARCHAR(64),
  `data` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO `users` (`username`, `password`) VALUES ('admin', 'admin123')
  ON DUPLICATE KEY UPDATE `username` = `username`;